### PR TITLE
added release drafter

### PR DESCRIPTION
**Pull request by PratikMane0112**
To simplify changelog creation, this PR adds a `release-drafter.yml` configuration file as referenced in [this document](https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc).

### **Description**
This PR introduces a `release-drafter.yml` file to automate the generation of release notes. The configuration:
- Extends the common `.github` template used across Jenkins repositories.
- Specifies a custom tag template format: `clone-workspace-scm-$NEXT_PATCH_VERSION`.

#### **Manual Testing**
1. **YAML Syntax Validation:**
   - Validated the `release-drafter.yml` file syntax using an online linter ([yamllint](https://yamllint.com/)).
   - Confirmed no syntax errors were detected.

#### **Automated Testing**
As this change introduces a configuration file and does not directly impact code or functionality, automated tests are not applicable.

### **Submitter Checklist**
- [x] Ensure you are opening from a **topic/feature/bugfix branch** (not the main branch).
- [x] Verify that the pull request title reflects the intended changelog entry.
- [x] Provide a clear and detailed description of the changes made.

### CODE REVIEW

**Comment by PratikMane0112** [comment]
@MarkEWaite sir, 

Please review the PR and suggest me any changes. I am just following this guide  to modernize the plugin which are ready for adoption - https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit?tab=t.0#heading=h.5kvkhdwxy3a 

If I am going in right way, can I add same changes for below plugins -
- gitee-plugin - (https://github.com/jenkinsci/gitee-plugin)
- emailext-template-plugin - (https://github.com/jenkinsci/emailext-template-plugin)

these plugins also not have `release-drafter.yml` file.

**Review by MarkEWaite — CHANGES_REQUESTED** [review]
Thanks, but a release drafter configuration is not needed for this plugin because it [releases new versions automatically](https://www.jenkins.io/doc/developer/publishing/releasing-cd/) when significant changes are merged to the master branch.  As part of that, the release drafter configuration is already [provided by the automated release](https://www.jenkins.io/doc/developer/publishing/releasing-cd/#configure-release-drafter), so it does not need to be configured in the repository.

Plugins that do not release automatically can benefit from release drafter, but it is not needed for plugins that are configured with automatic release.

The current release configuration for each plugin is stored in the [repository permissions updater](https://github.com/jenkins-infra/repository-permissions-updater/blob/master/permissions/plugin-clone-workspace-scm.yml).  When `cd.enabled` is `true`, then automated releases are enabled.

**Comment by PratikMane0112** [comment]
Ok @MarkEWaite Sir, I understood. So are the all plugins already been modernize ? 
Is there any benefit to follow this guideline further to contribute - https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit?tab=t.0#heading=h.5kvkhdwxy3a

Or should I look for other issues to contribute ?

**Comment by MarkEWaite** [comment]
> Ok @MarkEWaite Sir, I understood. So are the all plugins already been modernize ?

No, all plugins have not been modernized, but most actively maintained plugins have been modernized.

> Is there any benefit to follow this guideline further to contribute - https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit?tab=t.0#heading=h.5kvkhdwxy3a

I created that document to record improvements while I was learning about them.  The most applicable of the plugin improvement ideas from that document are now included in the [Improve a Plugin tutorial series](https://www.jenkins.io/doc/developer/tutorial-improve/).  I still reference items in that document as a plugin maintainer, but I'm not sure that the ideas in that document are detailed enough for a new contributor to understand the cases where they apply and the cases where they do not apply.

> Or should I look for other issues to contribute ?

I think you should look for other issues to contribute.  The two lists I recommend as a first location are:

* [Friendly issues in Jira](https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=19342)
* [Good first issues in GitHub](https://github.com/search?q=org%3Ajenkinsci+org%3Ajenkins-infra+is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22)

**Comment by PratikMane0112** [comment]
Ok @MarkEWaite sir, thanks for suggestion. I will look over other issues you suggested. Thanks !!!!

**Pull request closed without merging**
